name: Yellow Leo
favicon: null
layout_spectrum: 0.37478
typography_spectrum: 0.4942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#edc09f'
    - '#c1ab00'
    - '#310f06'
    - '#428ad6'
  brandStrength: 0.5
  lightness: 0.672845
  saturation: 0.584517
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
